### ISSUE TITLE
Global tables create conflict with subtables

### ISSUE THREAD

**Issue by sparrc** [naoina/toml#18]
I'm getting an error parsing the [tags] sections in valid toml that looks like this:

``` toml
# Global tags
[tags]
  shipment = "2a"

# Create list of tables with subtables

[[fruits.apple]]
  type = "red delicious"
  [fruits.apple.tags]
    PLU = 4555

[[fruits.apple]]
  type = "granny smith"
  [fruits.apple.tags]
    PLU = 4556
```

If I remove the global `[tags]` heading, or if I only set `[fruits.apple.tags]` once, the parsing works.

Below are some scripts for reproducing:

``` go
package main

import (
    "fmt"

    "github.com/naoina/toml"
)

// Global tags cause failure
const fruits = `
# Global tags
[tags]
  shipment = "2a"

# Create list of tables with subtables

[[fruits.apple]]
  type = "red delicious"
  [fruits.apple.tags]
    PLU = 4555

[[fruits.apple]]
  type = "granny smith"
  [fruits.apple.tags]
    PLU = 4556
`

func main() {
    _, err := toml.Parse([]byte(fruits))
    if err != nil {
        fmt.Println(err.Error())
        return
    }
}
```

it outputs:

```
% go run /tmp/config.go
toml: line 15: table `fruits.apple.tags' is in conflict with normal table in line 10
```

_but_ if I take out the global `[tags]` table, it works:

``` go
package main

import (
    "fmt"

    "github.com/naoina/toml"
)

// This one works!
const fruits = `
# Create list of tables with subtables

[[fruits.apple]]
  type = "red delicious"
  [fruits.apple.tags]
    PLU = 4555

[[fruits.apple]]
  type = "granny smith"
  [fruits.apple.tags]
    PLU = 4556
`

func main() {
    _, err := toml.Parse([]byte(fruits))
    if err != nil {
        fmt.Println(err.Error())
        return
    }
}
```

or if I remove one of the `[fruits.apple.tags]` sections, it also parses OK:

``` go
package main

import (
    "fmt"

    "github.com/naoina/toml"
)

// This one works!
const fruits = `
# Create list of tables with subtables

[[fruits.apple]]
  type = "red delicious"

[[fruits.apple]]
  type = "granny smith"
  [fruits.apple.tags]
    PLU = 4556
`

func main() {
    _, err := toml.Parse([]byte(fruits))
    if err != nil {
        fmt.Println(err.Error())
        return
    }
}
```
